### ISSUE TITLE
s/w/ord source missing

### ISSUE THREAD

**Issue by thexkey** [rebane2001/txnor-server#1]
hi, is it possible to upload the code behind `s/w/ag`?

**Comment by rebane2001** [comment]
The code is available, check chessgame.py.

**Comment by thexkey** [comment]
sorry, my phone auto corrected the sword command to swag, is the `s/w/ord` source available?

**Comment by rebane2001** [comment]
Not at this time

**Comment by afkvido** [comment]
So you mean PART OF IT IS CLOSED SOURCE?

# >:(

**Comment by rebane2001** [comment]
I could (and should) push it up here, but some assets (such as the Discord font) I cannot redistribute.

**Comment by afkvido** [comment]
ah, ok.

_time to pirate some discord fonts and make a fork lmao_

**Comment by thexkey** [comment]
let me know how that goes

**Comment by afkvido** [comment]
`not at this time`

**Comment by Kame03** [comment]
maybe use some different font in the source you post here?

**Comment by thexkey** [comment]
🤔

**Comment by rebane2001** [comment]
Added in 3b848dc0b68cc8196ce49a80a529be82d33272e1

**Comment by thexkey** [comment]
Amazing.
