### ISSUE TITLE
Chess sometimes throws random boards and turning king doesn't work

### ISSUE THREAD

**Issue by ggtylerr** [rebane2001/txnor-server#2]
As the title suggests, in chess, it will sometimes throw a random board that is completely not related. *(This can be solved by doing the same move again.)* An example:
***Expected***
![image](https://user-images.githubusercontent.com/28498877/177454171-029f20c8-9d9e-4011-a87f-4e24d95a711d.png)
***Outcome***
![image](https://user-images.githubusercontent.com/28498877/177454279-3ff92593-7ba5-478e-be39-5ee73fb5cb8b.png)

Also, the functionality to turn a pawn to a king is completely unimplemented.
![image](https://user-images.githubusercontent.com/28498877/177454406-a7b9cf2f-8e95-4479-8790-38e4cab12b33.png)
Note how I've tried 5 times to move it, and yet all 5 times did not work.

<details>
<summary>Full URLs</summary>
expected image:

```
https://txnor.com/vieagd6d7d6d7a5a6a5a6d5d6d5d6d4d5a4a5f3g3f3g3e3f3e4e5e4e5a2a3a3a4a3a4d3e3d3e3c2d3c3c2d2c3c8c2c8c2b8c8b8c8b2b8a6c8a6c8f1a6d3d4d3d4f3e4f3e4b7b2f2f3e1d2e1d2c7b7c1c7c5d6b4c5d4c5d4c5b2b4a1c1c3d4f3d4f3d4b3b2e2e4e2e4d1b3d2c3d2c3c2c3c2c3b2a3c1d2d3d4d2d3e5f3b5a3c3b5f3e5g1f3b1c3/caught-in-sussy4k-omgomg-gif-21922925
```

outcome image:
```
https://txnor.com/vieagd6d7a5a6a5a6d5d6d5d6d4d5a4a5f3g3f3g3e3f3e4e5e4e5a2a3a3a4a3a4d3e3d3e3c2d3c3c2d2c3c8c2c8c2b8c8b8c8b2b8a6c8a6c8f1a6d3d4d3d4f3e4f3e4b7b2f2f3e1d2e1d2c7b7c1c7c5d6b4c5d4c5d4c5b2b4a1c1c3d4f3d4f3d4b3b2e2e4e2e4d1b3d2c3d2c3c2c3c2c3b2a3c1d2d3d4d2d3e5f3b5a3c3b5f3e5g1f3b1c3/caught-in-sussy4k-omgomg-gif-21922925
```

pawn to king:
```
https://txnor.com/vieaga7a8a7a8a7a8a7a8a7a8a6a7d6d7d6d7a5a6a5a6d5d6d5d6d4d5a4a5f3g3f3g3e3f3e4e5e4e5a2a3a3a4a3a4d3e3d3e3c2d3c3c2d2c3c8c2c8c2b8c8b8c8b2b8a6c8a6c8f1a6d3d4d3d4f3e4f3e4b7b2f2f3e1d2e1d2c7b7c1c7c5d6b4c5d4c5d4c5b2b4a1c1c3d4f3d4f3d4b3b2e2e4e2e4d1b3d2c3d2c3c2c3c2c3b2a3c1d2d3d4d2d3e5f3b5a3c3b5f3e5g1f3b1c3/caught-in-sussy4k-omgomg-gif-21922925
```

</details>

**Comment by rebane2001** [comment]
I don't think there is any way to fix it without breaking compatibility
