### ISSUE TITLE
s/w/ord all enemies

### ISSUE THREAD

**Issue by DaInfLoop** [rebane2001/txnor-server#3]
What enemies are there available for `s/w/ord` and how can I get each of them?

**Comment by fox3000foxy** [comment]
I think its based on characters after /vieord/.

**Comment by fox3000foxy** [comment]
> I think its based on characters after /vieord/.
its like a seed, which determines enemies, and actions of enemies
> yes, its possible to predict all actions

**Comment by DaInfLoop** [comment]
> I think its based on characters after /vieord/.

Yeah, but what enemies are there

**Comment by fox3000foxy** [comment]
idk

**Comment by fox3000foxy** [comment]
ask it to @rebane2001
