### ISSUE TITLE
s/e/x wont work if theres special characters

### ISSUE THREAD

**Issue by BastelPichi** [rebane2001/txnor-server#6]
Discord s/e/x won't work if you have an gif that has special characters, e.g. `ä`, `ö` or `ü` (or their url-encoded version). The given image is just the noise thingy image.

For example:
https://tenor.com/view/lachen-merkel-bundestag-fr%C3%B6hlich-angela-merkel-gif-19641894

Just shows as:
![grafik](https://user-images.githubusercontent.com/63782569/210177892-a3800688-3ad1-4c4a-ba7b-89e28fa8e869.png)

**Comment by rebane2001** [comment]
Fixed in 9be1672bf6247c42970988f901a531b65907585b

**Comment by BastelPichi** [comment]
thx, awesome project!
